### ISSUE TITLE
[FEATURE]  How to remove flaky tests from slack report? 

### ISSUE THREAD

**Issue by sianka** [ryanrosello-og/playwright-slack-report#113]
**Is your feature request related to a problem? Please describe.**
I'd like to remove flaky tests from the report overview in slack. 

**Describe the solution you'd like**
I've tried to experiment with statuses, but there is no flaky one, so I'd need a solution how to do it. 
As you can see from the screenshots provided, in the main screen of the report I have 2 tests (flaky + failed), but I'd like to see the same result I have in the thread (only 1 failed test). Thanks

**Additional context**
<img width="381" alt="Screenshot 2024-03-18 at 16 43 38" src="https://github.com/ryanrosello-og/playwright-slack-report/assets/33104843/01d159d3-9e25-4168-9c9e-4b0f3aa6a186">
<img width="395" alt="Screenshot 2024-03-18 at 16 43 42" src="https://github.com/ryanrosello-og/playwright-slack-report/assets/33104843/6e2c4047-e51a-493c-b929-1a2d77fe60a2">

**Comment by ryanrosello-og** [comment]
@sianka can you try this https://github.com/ryanrosello-og/playwright-slack-report/issues/100#issuecomment-1974059482

**Comment by sianka** [comment]
@ryanrosello-og yes, thanks, I tried this solution, but it didn't help to remove the titles of flaky tests. 
I need to remove the title if a test passes from the second try. 
Also, I tried this solution   ```
for (const t of tests) {
    if ((t.status === 'failed' || t.status === 'timedOut') && t.retry == 0) {
      const testTitle = `:pushpin: ${t.name.split('@')[0].trim()}`;
```

but it didn't work either

Here is the screenshot how it looks after implementing your solution: 
<img width="225" alt="Screenshot 2024-03-21 at 16 49 52" src="https://github.com/ryanrosello-og/playwright-slack-report/assets/33104843/a33eb86c-8160-4501-9972-93d3077edc45">

**Comment by ryanrosello-og** [comment]
@sianka what if you change your logic slightly:

from 

```typescript
for (const t of tests) {
    if ((t.status === 'failed' || t.status === 'timedOut') && t.retry == 0) {
      const testTitle = `:pushpin: ${t.name.split('@')[0].trim()}`;
```


to 

```typescript
for (const t of tests) {
    if ((t.status === 'failed' || t.status === 'timedOut') && t.retry == [retries as per your playwright config e.g. 2]) {
      const testTitle = `:pushpin: ${t.name.split('@')[0].trim()}`;
```

that way, it will only report on the tests that have failed their last attempt.

**Comment by sianka** [comment]
@ryanrosello-og thank you, it worked!

**Comment by sianka** [comment]
@ryanrosello-og the solution worked for removing flaky tests titles, but it also removed failed ones.
