### ISSUE TITLE
Sending test results failed with channel_not_found

### ISSUE THREAD

**Issue by azad-derakhshani-GS** [ryanrosello-og/playwright-slack-report#13]
We just set up the slack reporter as an app in our Slack workspace, installed the npm module and ran the tests with the OAuth token generated by the app, however the Slack reporter seems to be unable to find the channel I set up for it:

`[
  {
    "channel": "test-results",
    "outcome": "❌ Message not sent to test-results \r\n An API error occurred: channel_not_found"
  }
]
`

We just changed the channel visibility to private, could that be the reason why? Does the channel need to be public for the bot to work? Or could it be some other issue?

**Comment by ryanrosello-og** [comment]
hey @azad-derakhshani-GS 

I was able to reproduce this.
![2022-09-22_09-14-02](https://user-images.githubusercontent.com/50574915/191626534-140beeac-2080-468d-afff-0a3288de52ad.png)

Yes, you are correct.  The channel you are posting to will need be Public.  Unfortunately, there doesn't seem to be an easy way to convert a private change into a public channel.

"https://twitter.com/slackhq/status/835541575144992769?lang=en"

You may need to create another **_public_** channel instead.

I'll update the instructions in the readme to mention this restriction.

**Comment by azad-derakhshani-GS** [comment]
Ah ok thanks, that's good to know!
Oh wow didn't know turning them back to public is not possible, what an odd restriction of Slack. I'll ask our Slack admins to create a new channel for me then.

**Comment by azad-derakhshani-GS** [comment]
Ok it worked with a public channel now!
Closing this issue.

However I've got a few questions regarding the custom layout, I followed the instructions but my IDE throws some errors even when I just copy-paste the examples.
Should I just create an issue for that - possibly with some suggestions for the documentation - or contact you elsewhere? @ryanrosello-og
