### ISSUE TITLE
How to hide flaky tests from the report?

### ISSUE THREAD

**Issue by pavelkostyurin** [ryanrosello-og/playwright-slack-report#139]
### Bug description

```
[
    './node_modules/playwright-slack-report/dist/src/SlackReporter.js',
    {
      channels: [zzzz],
      sendResults: 'always',
      maxNumberOfFailuresToShow: 5,
      slackLogLevel: 'error',
      disableUnfurl: true,
      showInThread: true,
      separateFlaky: undefined
    }
  ]
  ```

### How to reproduce (please include a snippet of your Playwright Slack Reporter configuration)

Is it possible to not output flaky tests counter at all? I believe it used to work when I first tried this plugin, but now I always get yellow coin icon.

### Environment & setup

Linux Ubuntu 22.04, node v.18.18.0

### playwright-slack-report version

```
"playwright-slack-report": "^1.1.81"
```

**Comment by ryanrosello-og** [comment]
@pavelkostyurin are you referring to this? or something else?



<img width="459" alt="2024-06-30_19-05-58" src="https://github.com/ryanrosello-og/playwright-slack-report/assets/50574915/2e99a2b6-0460-48ee-8ff9-35b3d7816484">

You can remove this information by defining your own layout here...

https://github.com/ryanrosello-og/playwright-slack-report?tab=readme-ov-file#-define-your-own-slack-message-custom-layout
