### ISSUE TITLE
When using `on-failure` reports are still being sent for Flaky tests

### ISSUE THREAD

**Issue by fspinillo** [ryanrosello-og/playwright-slack-report#152]
### Bug description

I have a CLI report configured to only send results with `on-failure` but reports are still being sent when a Flaky test is being detected.  My Playwright configuration is set to retry tests 1 time and I'm using merged results to generate the JSON for the report. 

------

When inspecting the results, there was 2 failed and 2 flaky tests. However in the thread with the errors, it was showing 4 tests. 

1 failed test had 2 statuses of `failed`, and the other one had 2 statues of `timedOut`. I set both of those failed tests to have a status of `passed`. After doing this I sent the report again and it still appeared in Slack.

On one of the flaky tests I set `results[0].status` to `passed` from `failed`, and then resent the report. The report was resent, but this time only 1 test was shown in the thread.

It seems like even with `on-failure` set, the message will still be sent if the first test run has a failure or time out despite being marked as `flaky` in tests.status. The below screenshot of the JSON schema will still trigger a message to be sent to slack:
![image](https://github.com/user-attachments/assets/6497039f-d4de-465d-b1a5-85038f3c66ff)

### How to reproduce (please include a snippet of your Playwright Slack Reporter configuration)

My CLI Config looks like so:
```
{
  "sendResults": "on-failure",
  "slackLogLevel": "error",
  "sendUsingBot": {
    "channels": ["e2e-report-testing"]
  },
  "showInThread": true,
  "meta": [
    { "key": "workflow", "value": "WORKFLOW-NAME" },
    { "key": "author", "value": "AUTHOR" },
    { "key": "commit", "value": "COMMIT" },
    { "key": "results", "value": "12345" }
  ],
  "maxNumberOfFailures": 4,
  "disableUnfurl": true,
  "customLayout": {
    "source": "./slack-reporter/cli_block_with_meta.ts",
    "functionName": "generateCustomLayoutSimpleMeta"
  }
}
```

Snippet of JSON
```
[
                {
                  "timeout": 15000,
                  "annotations": [],
                  "expectedStatus": "passed",
                  "projectName": "chrome",
                  "results": [
                    {
                      "workerIndex": 0,
                      "status": "timedOut",
                      "duration": 4650,
                      "error": {
                        "message": "Error: locator.click: Target page, context or browser has been closed\nBrowser logs:\n\n<launching> waiting for element to be visible, enabled and stable\u001b[22m\n",
                        "stack": "Error: locator.click: Target page, context or browser has been closed\nBrowser logs:\n\n<launching> /my-test.spec.ts:56:57",
                        "location": {
                          "file": "/my-test.spec.ts",
                          "column": 57,
                          "line": 56
                        },
                        "snippet": "'file type'\u001b[39m\u001b[0m"
                      },
                      "errors": [
                        {
                          "location": {
                            "file": "/my-test.spec.ts",
                            "column": 57,
                            "line": 56
                          },
                          "message": "Error: locator.click: Target page, context or browser has been closed\nBrowser logs:\n\n<launching> cmy-test.spec.ts:56:57"
                        }
                      ],
                      "stdout": [],
                      "stderr": [],
                      "retry": 0,
                      "startTime": "2024-07-09T19:09:59.626Z",
                      "attachments": [
                        {
                          "name": "trace",
                          "contentType": "application/zip",
                          "path": "/home/runner/work/web-app/web-app/apps/playwright/all-blob-reports/resources/bee533f6bcff42c5228f0e11a7e24e01130355a4.zip"
                        }
                      ],
                      "errorLocation": {
                        "file": "/__w/web-app/web-app/apps/playwright/tests/collections/collections-groups.spec.ts",
                        "column": 57,
                        "line": 56
                      }
                    },
                    {
                      "workerIndex": 1,
                      "status": "passed",
                      "duration": 6817,
                      "errors": [],
                      "stdout": [],
                      "stderr": [],
                      "retry": 1,
                      "startTime": "2024-07-09T19:10:05.490Z",
                      "attachments": []
                    }
                  ],
                  "status": "flaky"
                }
              ]
```

### Expected behavior

When set to `on-failure` a report should only be sent if there are failing tests, and not if all tests pass but a test is marked as `flaky`

### Environment & setup

- OS: MacOS and Linux
- Node.js version: 20.12.2

### playwright-slack-report version

```
1.1.81

```

**Comment by ryanrosello-og** [comment]
yeah I can reproduce it :( 

<img width="997" alt="2024-07-29_19-13-34" src="https://github.com/user-attachments/assets/27f89499-202f-4797-90a3-6b261585dd0a">


I'll need to take deeper look into this.  Leave it with me

**Comment by ryanrosello-og** [comment]
can you confirm a couple of things for me @fspinillo 

1. In your merged json result, would you be able to check if this `projects` array has data inside it? In particular, the `retries` key?

<img width="632" alt="2024-07-29_19-18-43" src="https://github.com/user-attachments/assets/e87ed9d8-20df-4559-8dfb-a113fa0ae9ac">


2. Please let me know what version Playwright you are using?

My suspicion is that the latest version of playwright may have tweaked the structure of the json output

**Comment by fspinillo** [comment]
Apologies for late reply, missed the notification.

> In your merged json result, would you be able to check if this projects array has data inside it? In particular, the retries key?

It's fully empty:
![image](https://github.com/user-attachments/assets/27728363-b7fc-4c06-b253-235d8d87dcaf)

> Please let me know what version Playwright you are using?

Version 1.45

**Comment by sufiyangorgias** [comment]
@ryanrosello-og same issue, any update on this. thx 👍
