### ISSUE TITLE
The amount of test(failed) is not correct when using test.fail

### ISSUE THREAD

**Issue by leonardolopez24** [ryanrosello-og/playwright-slack-report#155]
### Bug description

We are using `test.fail` in some tests and we are seeing that at the end of the tests the number of tests that failed is not correct, I think that here you could validate using expectedStatus before adding the test to the list of failures
I leave an example of the possible change here
 ```
async getFailures(): Promise<Array<failure>> {
    const failures: Array<failure> = [];
    for (const suite of this.result) {
      for (const test of suite.testSuite.tests) {
       if ((test.status === 'failed' && test.expectedStatus !== 'failed') || test.status === 'timedOut') {
          // only flag as failed if the last attempt has failed
          if (test.retries === test.retry) {
            failures.push({
              suite: test.suiteName,
              test: ResultsParser.getTestName(test),
              failureReason: test.reason,
            });
          }
        }
      }
    }
    return failures;
  }
```
https://github.com/ryanrosello-og/playwright-slack-report/blob/56206e139c8577cf5e2d983e7bc6db0a1212f8bc/src/ResultsParser.ts#L170
https://playwright.dev/docs/api/class-test#test-fail

### Expected behavior

Tests marked with  test.fail should not be added to the failure list unless test.status is !== test.expectedStatus

### Environment & setup

- OS: --> Debian
- Node.js version: --> v20.14.0

### playwright-slack-report version

```
   "version": "1.1.3",
```

**Comment by ryanrosello-og** [comment]
@leonardolopez24 you are using a well out of date version.  Can you try upgrading to the latest and see what sort of results you get?

**Comment by leonardolopez24** [comment]
@ryanrosello-og We are still geting listed the test that has test.fail
Slack report
![image](https://github.com/user-attachments/assets/4a47957b-b8dc-4c35-a8fc-39a7bb172c90)
Monocart example: showing the expected values
![image](https://github.com/user-attachments/assets/49501830-b80e-49e7-9b4e-95839ad3ebcd)

**Comment by leonardolopez24** [comment]
I'm adding unit test, I'll let you know when it's done
