### ISSUE TITLE
Tweak summary stats to better cater for tests that have passed via retry

### ISSUE THREAD

**Issue by ryanrosello-og** [ryanrosello-og/playwright-slack-report#17]
Suggested by Juani in https://playwright.slack.com/archives/CSUHZPVLM/p1664487768358789?thread_ts=1662392151.519479&cid=CSUHZPVLM

![2022-09-30_08-10-34](https://user-images.githubusercontent.com/50574915/193151140-db0e9ee5-2101-443a-87ce-bf69587f7ff4.png)

**Comment by jgibo** [comment]
I think this will be fulfilled by my PR here https://github.com/ryanrosello-og/playwright-slack-report/pull/54
