### ISSUE TITLE
Attachments should be forwarded when only latest retry is kept

### ISSUE THREAD

**Issue by kalkun** [ryanrosello-og/playwright-slack-report#172]
### Bug description

Since the #166 squash the list of test failures to only include the latest retry, this also means that unless attachments are created on the last retry they are lost. 

It would be better to forward attachments, than losing them entirely - especially for tests that fails both on first attempt and any subsequent retries. 

```typescript
...
use: {
   screenshot: "only-on-failure"
}
```
_(from what I can tell the screenshot is not retaken on retries (?) )_

### Environment & setup

- OS: 
- Node.js version: 

### playwright-slack-report version

```
    "playwright-slack-report": "1.1.86",
```

**Comment by willbertSmillbert** [comment]
Are you sure you were previously getting the behaviour you desire? What you described is how playwright works out of the box. If you have the screenshot only on failure CLI option set, you will get a screenshot on the last retry. If a test fails, then passes later no screenshot will be taken. 

Maybe you can make a feature request to playwright to request a new screenshot option. maybe something like screenshot: on-every-retry

**Comment by kalkun** [comment]
I think you're right that this is with Playwright itself. I've since set the screenshot option to `on` to ensure that I have it. I think this issue can be closed, thanks for the reply 🙏
