### ISSUE TITLE
[FEATURE] Per-project channels

### ISSUE THREAD

**Issue by itspriddle** [ryanrosello-og/playwright-slack-report#173]
**Is your feature request related to a problem? Please describe.**

I am working in a playwright suite that uses projects to represent each app. I'd like a way to send Slack notifications to different channels depending on the project(s) being tested. This would allow me to have different teams triage those issues without things getting noisy for folks who didn't work on a specific project. 

I was able to get it working with environment variables, but that is non-standard and I'd like to be able to support this workflow with standard `npx playwright --project=app1` style commands. 

**Describe the solution you'd like**

Given a project config like:

```js
export default defineConfig({
  ...
  projects: [
    { name: "app1", ... },
    { name: "app2", ... }
  ]
});
```

I'd like a way to do something like:

```js
export default defineConfig({
  reporter: [
    [
      './node_modules/playwright-slack-report/dist/src/SlackReporter.js',
      {
        channelsByProject: {
          app1: ["#app1-alerts"],
          app2: ["#app2-alerts"],
        },
        onFailureChannelsByProject: {
          app1: ["#app1-failures"],
          app2: ["#app2-failures"],
        },
        onSuccessChannelsByProject: {
          app1: ["#app1-success"],
          app2: ["#app2-success"],
        },
      }
    ],
    ["list"],
  ]
});
```

---

If there's a creative way to do this today I am happy to try that. I did attempt adding a `reporter` key in the project definition but Playwright doesn't seem to support that.

**Comment by ryanrosello-og** [comment]
@itspriddle can you try creating a config file per project?
e.g. `npx playwright --config=playwright.config.app1.ts`
`npx playwright --config=playwright.config.app2.ts`

and then have whatever reporting config you need per config file ?
would this help you at all?

**Comment by itspriddle** [comment]
That would work in theory. I was kind of hoping for something more automatic that wouldn't require extra knowledge outside of the Playwright docs for others to work with the suite.

My initial attempt with environment vars was something like:

```js
const channels = {
  app1: "#app1-alerts",
  app2: "#app2-alerts",
}

export default defineConfig({
  reporter: [
    [
      './node_modules/playwright-slack-report/dist/src/SlackReporter.js',
      {
        channels: [channels[process.env.APP]],
        ...
      }
    ]
  ]
});
```

I only really need Slack notifications in CI so I can just stick with that. I'd just hoped to be able to use standard Playwright commands rather than relying on env variables.

**Comment by itspriddle** [comment]
I ended up writing my own reporter since I wanted full control of everything. If you did want to implement this here, the magic for me was detecting the project from `test.titlePath()[1]` inside the reporter's `onTestEnd()` method; eg:

```
onTestEnd(test, result) {
  const project = test.titlePath()[1];
}
```

Thank you for putting together this project! It was very helpful to see how things worked to be able to write my own ❤️
