### ISSUE TITLE
Cannot send thread error list if more then 50.

### ISSUE THREAD

**Issue by exotlv** [ryanrosello-og/playwright-slack-report#180]
### Bug description

Slack Thread cannot be created if more then 50 errors there. Even if in config, I added: 100.
✅ Message sent to aqa-reports
[
  {
    "channel": "aqa-reports",
    "outcome": "✅ Message sent to aqa-reports",
    "ts": "1726119632.656559"
  }
]
Error in reporter Error: An API error occurred: invalid_blocks
    at platformErrorFromResult (/home/gitlab_ci_multi_runner/data/white-label/tests-ui/node_modules/@slack/web-api/src/errors.ts:119:5)
    at WebClient.<anonymous> (/home/gitlab_ci_multi_runner/data/white-label/tests-ui/node_modules/@slack/web-api/src/WebClient.ts:326:36)
    at Generator.next (<anonymous>)
    at fulfilled (/home/gitlab_ci_multi_runner/data/white-label/tests-ui/node_modules/@slack/web-api/dist/WebClient.js:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'invalid_blocks',
    errors: [ 'no more than 50 items allowed [json-pointer:/blocks]' ],
    response_metadata: { messages: [Array], scopes: [Array], acceptedScopes: [Array] }
  }
}

### How to reproduce (please include a snippet of your Playwright Slack Reporter configuration)

Playwright: 1.47.0
`const slackReporterOptions = {
  channels: ["aqa-reports"],
  sendResults: "always", // "always" , "on-failure", "off"
  slackLogLevel: "ERROR",
  disableUnfurl: true,
  showInThread: true,
  maxNumberOfFailuresToShow: 100,
  meta: [
    {
      key: 'Build run by',
      value: username || 'unknown_user',
    },
    {
      key: 'Branch',
      value: process.env.CI_COMMIT_REF_NAME || 'Unknown Branch',
    },
    {
      key: 'Job name',
      value: process.env.CI_JOB_NAME || 'Unknown Job', // Depending on your CI environment, this can be the branch name, build id, etc.
    },
    {
      key: 'Job Link',
      value: process.env.CI_JOB_URL || 'Unknown Job Link', // Depending on your CI environment, this should be the job URL.
    },
  ],
};`

### Environment & setup

GitLab

### playwright-slack-report version

```
1.1.86
```

**Comment by ryanrosello-og** [comment]
@exotlv this is enforced by the Slack api

![2024-09-13_05-32-48](https://github.com/user-attachments/assets/61ff7db8-eeb1-47e6-9dc4-c158948f9f10)
