### ISSUE TITLE
[README file] Issues related to Example 4: - Upload the attachments to directly to Slack

### ISSUE THREAD

**Issue by baron-15** [ryanrosello-og/playwright-slack-report#201]
### Bug description

In the **example 4: Upload the attachments to directly to Slack**, I ran into a few problems.

**First problem**
I noticed a few issues with the uploadFile function comparing to [Slack Web API page](https://tools.slack.dev/node-slack-sdk/web-api#upload-a-file).
1. `files.uploadV2` should be replaced with `filesUploadV2`
2. `return result.file` should be replaced with `return result.files`

**Second problem**
A part of the code started with `if (a.name === 'video' && file.permalink)` intended to publish the video that was uploaded to Slack into a channel as a video block. However, this was not working for me, as per [Slack API Video Block page](https://api.slack.com/reference/block-kit/blocks#video)'s Requirements section,
> video_url must not point to any Slack-related domain.

**Third problem (unverified)**
`file.permalink` mentioned above did not give return the correct data. Instead, I had to use `file[0].files[0].permalink`. So I speculate that this would also affect the image upload as well as the variable `file.name`.

### How to reproduce (please include a snippet of your Playwright Slack Reporter configuration)

When using the current example 4 codes in readme.

### Environment & setup

"@playwright/test": "^1.43.1",
    "@slack/types": "^2.12.0",
    "@types/node": "^20.12.3",
    "playwright-slack-report": "^1.1.72"

### playwright-slack-report version

1.1.72

**Comment by ryanrosello-og** [comment]
@baron-15 do you have time to create a pr for this?
