### ISSUE TITLE
How to force a field value to not break into multiple lines?

### ISSUE THREAD

**Issue by azad-resolver** [ryanrosello-og/playwright-slack-report#210]
I've been working with the Slack Reporter for quite a while and have been very pleased with its feature set. Our users very much appreciate its capabilities as well.

I've been using my own custom layout which includes various bits of meta data as well as some links - a total of 7 fields.
So that generates 3 pairs of values, and one single value at the end.
One of those links, depending on the value, can break into two lines though if the value is too long.
I've already put that field at the end (7th) so that it's the only field on the last line - so in theory it would have a lot of space to display the entire value on one line. But it still does the line-break.

![image](https://github.com/user-attachments/assets/4ec561a4-32d3-483a-816d-ccf6f34abeee)

Is there some way to force it to use the entire space? Or tell the layout that that particular field is allowed to be twice as wide?
If not, would it be possible to add such a feature (some sort of `wideLine` field option)?
That would definitely make it more visually appealing.

**Comment by ryanrosello-og** [comment]
@azad-resolver do you mind sharing your custom layout?

**Comment by azad-resolver** [comment]
> @azad-resolver do you mind sharing your custom layout?

Yeah sure! 
Just replaced part of the urls with "xyz" but apart from that it's this: 

```
import {Block, KnownBlock} from '@slack/types'
import {SummaryResults} from 'playwright-slack-report/dist/src'

export async function slackReporterLayout(summaryResults: SummaryResults, slackUserId: string): Promise<Array<KnownBlock | Block>> {
  const meta: {type: string; text: {type: string; text: string}}[] = []
  if (summaryResults.meta) {
    for (let i = 0; i < summaryResults.meta.length; i += 1) {
      const {key, value} = summaryResults.meta[i]
      meta.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*${key}*: \`${value}\``,
        },
      })
    }
  }
  const fullName = process.env.BUILD_USER as string
  const passedText = summaryResults.passed === 1 ? `${summaryResults.passed} test passed` : `${summaryResults.passed} tests passed`
  const failedText = summaryResults.failed === 1 ? `${summaryResults.failed} test failed` : `${summaryResults.failed} tests failed`
  const testExecutionText = process.env.TEST_EXECUTION_KEY ? `<https://xyz.atlassian.net/browse/${process.env.TEST_EXECUTION_KEY}|${process.env.TEST_EXECUTION_KEY}>` : '`Test Execution not provided`'

  return [
    {
      type: 'divider',
    },
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: summaryResults.failed === 0 ? `:large_green_circle: ${passedText}` : `:large_green_circle: ${passedText} \n:red_circle: ${failedText}`,
      },
      fields: [
        {
          type: 'mrkdwn',
          text: `*Tests*\n\`${process.env.TEST_TYPE_VALUE}\``,
        },
        {
          type: 'mrkdwn',
          text: `*Branch*\n<https://github.com/xyz/playwright/tree/${process.env.BRANCH}|${process.env.BRANCH}>`,
        },
        {
          type: 'mrkdwn',
          text: `*Test Execution*\n${testExecutionText}`,
        },
        {
          type: 'mrkdwn',
          text: `*Test Results*\n<https://qe-jenkins.staging.xyz.com/job/playwright/${process.env.JENKINS_BUILD_NUMBER}/Playwright-Test-Report/|Playwright Test Report (#${process.env.JENKINS_BUILD_NUMBER})>`,
        },
        {
          type: 'mrkdwn',
          text: `*Deployment Version*\n\`${process.env.DEPLOYMENT_VERSION}\``,
        },
        {
          type: 'mrkdwn',
          text: `*User*\n${slackUserId ?? fullName}`,
        },
        {
          type: 'mrkdwn',
          text: `*Server*\n<${process.env.WEBSITE_URL}|${process.env.WEBSITE_URL}>`,
        },
      ],
    },
    ...meta,
    {
      type: 'divider',
    },
  ]
}

```

**Comment by ryanrosello-og** [comment]
hey @azad-resolver 

Could you try moving the `Server` into its own section ...

<img width="1807" alt="2024-11-16_06-45-11" src="https://github.com/user-attachments/assets/c3bef9e4-ee3d-46c0-9e00-65e1bbe6b8a4">

The result should look like this:

<img width="1077" alt="2024-11-16_06-37-26" src="https://github.com/user-attachments/assets/72f82e77-6a38-4b3e-adca-1c6f8174a888">


If you want to further customize your layout, I suggest signing up for a free Slack account and have a play around with their [Block builder](https://api.slack.com/block-kit/building
)

**Comment by azad-resolver** [comment]
Oh nice, thanks! Moving it into its own section should do the trick.

But the Block Builder looks like a great long-term solution, I'll look into that as well. Thank you for your help!
