### ISSUE TITLE
[Question] would it be possible to choose to not send notifications in a development env?

### ISSUE THREAD

**Issue by OShalaby** [ryanrosello-og/playwright-slack-report#22]
What I am trying to achieve is that no notifications get delivered to slack if I am running the tests locally as opposed to automated CI runs, is there a certain flag or way that could help me achieve this?

Thank you

**Comment by ryanrosello-og** [comment]
similar to https://github.com/ryanrosello-og/playwright-slack-report/issues/23

It depends on your Build server, most build servers will have a `CI` environment variable pre-configured.

For example, [Buildkite exposes a `CI` environment variabl](https://buildkite.com/docs/pipelines/environment-variables#CI)e which you can then call within your config to determine whether to send results.  This variable should not exist (or  can be set to `false`) in your local development environment.


```
  reporter: [
    [
      {
        sendResults: process.env.SEND_RESULTS && process.env.CI === 'true' ? "always": "off"
      },
    ],
  ],
```
