### ISSUE TITLE
[Question] How could I improve the auto triggering of the notifications?

### ISSUE THREAD

**Issue by OShalaby** [ryanrosello-og/playwright-slack-report#23]
in my case I list the cases before I run them i.e.
`npx playwright test --list && npx playwright test`
the issue here is the module sends 2 notifications, 1 after listing with stats of zeros and another (correct one) notification after the tests are executed

**Comment by ryanrosello-og** [comment]
hey @OShalaby 
You could try passing an environment variable to your commands?

`SEND_RESULTS=false npx playwright test --list && SEND_RESULTS=true npx playwright test`

```
  reporter: [
    [
      {
        sendResults: process.env.SEND_RESULTS.toLowerCase() === 'true' ? "always": "off"
      },
    ],
  ],
```

**Comment by OShalaby** [comment]
Hi Ryan! 
Thanks a lot for your reply, the CI part does the job for me in #22 (I am using Jenkins), this one seems very straight forward, it does not do the job for me though, the env var `SEND_RESULTS` is ignored even though it shows in the logs. so I have:

```
reporter: [
    [
      "./node_modules/playwright-slack-report/dist/src/SlackReporter.js",
      {
        channels: ["qc-automation"], // provide one or more Slack channels
        sendResults: process.env.SEND_RESULTS && process.env.CI === 'true' ? "always": "off", // "always" , "on-failure", "off"
        layoutAsync: generateCustomLayoutAsync,
        maxNumberOfFailuresToShow: 4,
        meta: [
          {
            key: 'node_env',
            value: process.env.HOME ,
          },
        ],
      },
    ],
    ['line'], 
    ['allure-playwright'],
  ]
  ```
  
  then I run:
  ```SEND_RESULTS=false npx playwright test --list && SEND_RESULTS=true npx playwright test```
  
  I get: 
  ```
  + SEND_RESULTS=false npx playwright test --list
Listing tests:
  ...
Total: 6 tests in 1 file
[DEBUG]  web-api:WebClient:0 initialized
[DEBUG]  web-api:WebClient:0 apiCall('chat.postMessage') start
...
```
and I get a slack notification of zeros still...

**Comment by OShalaby** [comment]
I have been debuggin for a while now...and while I cannot exactly show what is a string and what is an actual boolean value when I execute from the CI, it is definitely something to do with the evaluation of the if statement. 
I tried stringifiying(`String(x)`) and converting to bool (`Boolean(x)`) on different vars and even the `true` itself and changing the operator between `==` and `===` but in order to get correct results and after some researching I sadly ended up doing:
`JSON.parse(String(process.env.SEND_RESULTS)) && JSON.parse(String(process.env.CI)) === JSON.parse(String(true))`
`JSON.parse` seem to do the trick, the `String()` is added there for linting issues because the vars are undefined unless I execute

**Comment by ryanrosello-og** [comment]
Nice, good to hear its working for you.

There are other options here which is to use multiple playwright config files:

`playwright.local.ts` < utilized when developing tests locally

```
reporter: [
    [
      "./node_modules/playwright-slack-report/dist/src/SlackReporter.js",
      {
        ...
        sendResults: "off"
        ...
      },
    ]
  ]
```

`playwright.list_all_tests.ts` < point to this config file when running playwright with the `--list` param

```
reporter: [
    [
      "./node_modules/playwright-slack-report/dist/src/SlackReporter.js",
      {
        ...
        sendResults: "off"
        ...
      },
    ]
  ]
```

`playwright.jenkins.ts` < use this config file when running tests on Jenkins

```
reporter: [
    [
      "./node_modules/playwright-slack-report/dist/src/SlackReporter.js",
      {
        ...
        sendResults: "always"
        ...
      },
    ]
  ]
```
