### ISSUE TITLE
[Question] How could I send an alert when CI fails because of the timeout-minutes setting?

### ISSUE THREAD

**Issue by brunojbarros** [ryanrosello-og/playwright-slack-report#24]
I wait for 10 seconds for assertion and 20 seconds for the test and my timeout in CI is 15 minutes.

The problem is when I have many tests failing in CI (because one was made and it breaks the tests), the execution time reaches 15 minutes and the tests stop running, but I don't get any alert in Slack about this. How can I fix this? I only want to be notified when at least one test fails (I'm currently using "on failure") or then the tests execution stops due to my timeout-minutes setting in .yml.

```
# playwright.yml

jobs:
  test:
    name: "Run automated tests"
    timeout-minutes: 15
# other config
```

```
// playwright.config.ts
const config: PlaywrightTestConfig = {
  testDir: "./tests",
  timeout: 20 * 1000,
  expect: {
    timeout: 10000,
  },
  reporter: process.env.CI
    ? [
        [
          "./node_modules/playwright-slack-report/dist/src/SlackReporter.js",
          {
            channels: ["playwright-alerts"], // provide one or more Slack channels
            sendResults: "on-failure"
            layoutAsync: generateCustomLayoutAsync,
          },
        ],
        ["html"],
      ]
    : [
        ["html"],
      ],
// other config...
};

export default config;
```

**Comment by ryanrosello-og** [comment]
@brunojbarros unfortunately this is beyond the capabilities of the library since it relies on the results generated by playwright.  If your CI timeouts before Playwright has a chance to generate the results then no notification will be sent.  My suggestion would be to read up on the doco of your build system and see if it has an ability to send build failures on timeout.

**Comment by brunojbarros** [comment]
@ryanrosello-og 
thanks for answering.

I was able to send an alert using when it happens using [slack-notify](https://github.com/marketplace/actions/) 😄
