### ISSUE TITLE
[Question] How to get more details out of errors through slack notifications from CI just like it is produced from local runs?

### ISSUE THREAD

**Issue by OShalaby** [ryanrosello-og/playwright-slack-report#25]
Hi @ryanrosello-og 

The notifications I get on slack from Jenkins are not descriptive like when the tests are run locally, how can I change that?

When I run locally with failed cases, on slack I would get:
<img width="668" alt="Screenshot 2023-02-21 at 11 15 34 AM" src="https://user-images.githubusercontent.com/55599154/220302146-d1e285d4-e9f4-4067-abbd-1b50b635b5a7.png">

but when I run from Jenkins, I get:
<img width="656" alt="Screenshot 2023-02-21 at 11 16 32 AM" src="https://user-images.githubusercontent.com/55599154/220302281-54e26c3a-a805-4073-b7fa-2acd027599e4.png">

my custom layout file:
```
import { Block, KnownBlock } from "@slack/types";
import { SummaryResults } from "playwright-slack-report/dist/src";

export async function generateCustomLayoutAsync (summaryResults: SummaryResults): Promise<Array<KnownBlock | Block>> {
  const { tests } = summaryResults;
  // create your custom slack blocks

  const header = {
    type: "header",
    text: {
      type: "plain_text",
      text: "🎭 *Playwright Test Results*",
      emoji: true,
    },
  };

  const summary = {
    type: "section",
    text: {
      type: "mrkdwn",
      text: `✅ *${summaryResults.passed}* | ❌ *${summaryResults.failed}* | ⏩ *${summaryResults.skipped}*`,
    },
  };

  const fails: Array<KnownBlock | Block> = [];

  for (const t of tests) {
    if (t.status === "failed" || t.status === "timedOut") {

      fails.push({
        type: "section",
        text: {
          type: "mrkdwn",
          text: `👎 *[${t.browser}] | ${t.suiteName.replace(/\W/gi, "-")}*`,
        },
      });

      const assets: Array<string> = [];

      if (assets.length > 0) {
        fails.push({
          type: "context",
          elements: [{ type: "mrkdwn", text: assets.join("\n") }],
        });
      }
    }
  }

  return [header, summary, { type: "divider" }, ...fails]
}
```

**Comment by ryanrosello-og** [comment]
hey @OShalaby , have a look at the definition of the `SummaryResults` here  https://github.com/ryanrosello-og/playwright-slack-report/blob/6bb3cbba853b100786a08a118981c2add90ec82c/src/index.ts#LL5C6-L5C6

You should be able to unpack the `failures` array to get more details
