### ISSUE TITLE
Missing init for slackOAuthToken in SlackReporter.ts

### ISSUE THREAD

**Issue by hananmalka** [ryanrosello-og/playwright-slack-report#27]
Missing:
`this.slackOAuthToken = slackReporterConfig.slackOAuthToken;`

This cause the error:
`Neither slackOAuthToken nor process.env.SLACK_BOT_USER_OAUTH_TOKEN were found
`

**Comment by ryanrosello-og** [comment]
@hananmalka can you let me know if you it works when using an environment variable `SLACK_BOT_USER_OAUTH_TOKEN` as opposed to setting a key in the config?

**Comment by hananmalka** [comment]
@ryanrosello-og 
When using the env variable `SLACK_BOT_USER_OAUTH_TOKEN` it **does works** but I prefer to set it in the config file

**Comment by ryanrosello-og** [comment]
attempt to fix here https://github.com/ryanrosello-og/playwright-slack-report/pull/28
@hananmalka try v1.1.1

**Comment by hananmalka** [comment]
@ryanrosello-og tried v1.1.1 - Still getting the error.

The change you made doesn't reflect on`SlackReporter.js` file under `dist/src`

**Comment by hananmalka** [comment]
@ryanrosello-og Any update with this one?

**Comment by ryanrosello-og** [comment]
@hananmalka try v1.1.2
Seems something got messed up publishing the npm package.

**Comment by hananmalka** [comment]
@ryanrosello-og 
Thanks. It works now with v 1.1.2
