### ISSUE TITLE
Is there a way to use this playwright-slack-report while running playwright tests with cucumber-js runner?

### ISSUE THREAD

**Issue by Latika-Soni13** [ryanrosello-og/playwright-slack-report#31]
Is there a way to use this playwright-slack-report while running playwright tests with cucumber-js runner?
As a part of my framework i wanted to send report and screenshots to slack but i am running through cucumber-js

**Comment by ryanrosello-og** [comment]
@Latika-Soni13 unfortunately this package was purely built for Playwright only.
