### ISSUE TITLE
[Question] Is there any way to share the failures in a thread created under the message sent by the report?

### ISSUE THREAD

**Issue by miguelofbc** [ryanrosello-og/playwright-slack-report#34]
Is there any way to share the failures in a thread created under the message sent by the report?

The idea around this suggestion is reducing verbosity on the message we are sending to the team.

<img width="681" alt="Screenshot 2023-05-02 at 14 27 15" src="https://user-images.githubusercontent.com/22458228/235681790-3d7c07ff-bbd6-40bb-9482-c878e02f42b6.png">

The highlighted section would go to a thread under the message with the results summary.

**Comment by ryanrosello-og** [comment]
I'll  do some googling and see if they have an endpoint for this.

**Comment by miguelofbc** [comment]
Found this one: https://api.slack.com/messaging/sending#threading

**Comment by ryanrosello-og** [comment]
It seems doable, here's my initial attempt at this ...

![image](https://user-images.githubusercontent.com/50574915/236672760-31471bda-8af4-4b6a-8089-922c60a7efd9.png)

Just having a think about what to display though, I guess we can keep it simple initially as per your example above:

**Failed test name**
> Stack trace (first 100 characters)

I will also need to add an extra config key (boolean - defaulted to false), something like `summarizeFailuresInThread`

**Comment by ryanrosello-og** [comment]
added in https://github.com/ryanrosello-og/playwright-slack-report/releases/tag/v1.1.14
