### ISSUE TITLE
Wrong test count in slack when using playwright-slack-reporter from Bitbucket pipeline

### ISSUE THREAD

**Issue by Alona-T** [ryanrosello-og/playwright-slack-report#49]
I do use standard setup for playwright-slack-reporter in my config

![image](https://github.com/ryanrosello-og/playwright-slack-report/assets/63534112/11fb6852-2317-46b8-89d5-b93f316f9745)

For some reason when i run tests from Bitbucket - i do have wrong test pass/fail/skip count in case i do have retries set 

  **retries: process.env.CI ? 2 : 0,**

![image](https://github.com/ryanrosello-og/playwright-slack-report/assets/63534112/426d5614-8651-43d0-8bf9-5161858f4091)

If i do it from local - there are no issues

Is there a way to fix it when run on Bitbucket?

**Comment by ryanrosello-og** [comment]
hey @Alona-T ,
I would recommend having 2 playwright config files: 1 for your local and the other for Bitbucket, that way you wouldn't need to do any ternary logic in your config.

Can you try running the Playwright reporter by itself on Bitbucket and see what results you get?
And then try re-running it using just the normal html reporter and then see what results you get?

**Comment by Alona-T** [comment]
@ryanrosello-og 
I tried to divide configs and added one for CI specifically using:
  retries: 2,
  workers: 1,

Also tried to run on CI same config with html report only - same wrong result

What i do find weird is - it does retry on passed tests as well (and i suspect it calculates these retries for some reason and sending that count to slack
![image](https://github.com/ryanrosello-og/playwright-slack-report/assets/63534112/2fa18794-f45e-4a39-bf69-21a4ac57282b)

So as far as i see failed test cases count is shown correctly in slack however passed and skipped - they are not. So maybe you guys can support it in your code where retries for same test case will be counted as 1 for all type of results?

**Comment by Alona-T** [comment]
@ryanrosello-og i actually tried to run plain playwright-slack-report without any custom reports locally with 2 retries and it gave me wrong calculation for skipped and passed when there is a failure present (check point 2)

If there are no failures - it did give correct count (check point 1)


![image](https://github.com/ryanrosello-og/playwright-slack-report/assets/63534112/2bc8f92a-b7e7-4102-83cb-064db6dbe7aa)

In terms of tests - i do have describe/test structure, nothing super complicated being honest

**Comment by miguelofbc** [comment]
Thanks for reporting @Alona-T ! I am experiencing the same @ryanrosello-og . The retries are messing up the counting for skipped.

**Comment by ryanrosello-og** [comment]
@Alona-T , struggling to reproduce this.
![image](https://github.com/ryanrosello-og/playwright-slack-report/assets/50574915/aa32ef8a-495c-4041-9457-fc70df5c1594)


This is my playwright config:

```typescript
import type { PlaywrightTestConfig } from "@playwright/test";
import { devices } from "@playwright/test";

const config: PlaywrightTestConfig = {
  testDir: "./tests",
  timeout: 30 * 1000,
  expect: {
    timeout: 5000,
  },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: 2,
  workers: 1,
  reporter: [
    ["dot"],
    [
      "./node_modules/playwright-slack-report/dist/src/SlackReporter.js",
      {
        channels: ["chan-chan"],
        sendResults: "always", // "always" , "on-failure", "off",
        meta: [
          {
            key: "Branch",
            value: "feature/test-slack-report",
          },
          {
            key: "Build",
            value: "v1.08-RC_2331150.033",
          },
        ],
      },
    ],
    ["html"],
  ],
  use: {
    actionTimeout: 0,
    trace: "on-first-retry",
    screenshot: "only-on-failure",
    video: "retain-on-failure",
  },
  projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
      },
    },
  ],
};

export default config;

```


Can you tell me a little bit more about your project?

- Are you using projects in the playwright config?
- Are you using the `page` supplied by playwright or are you handling the creation of browsers yourself?
- Are you using serial mode within your tests?
- How many workers are you using?

**Comment by Alona-T** [comment]
@ryanrosello-og 
**Are you using projects in the playwright config?** 

- i am not sure i have any as i do use similar config structure as you shared

**Are you using the page supplied by playwright or are you handling the creation of browsers yourself?** 

- this particular error was in API project (no browsers involved)

**Are you using serial mode within your tests?** 

- Yes we do use it
- **Example:**
`test.describe.serial('Test name', () => {}` or 

`test.describe.configure({ mode: "serial" });
test.describe.serial(`POST \/execute for unauthed user @coins`, () => {}`

**How many workers are you using?** 

- 1 worker

**Comment by ryanrosello-og** [comment]
I believe this will be fixed by https://github.com/ryanrosello-og/playwright-slack-report/pull/54

Please try v1.1.24 Release @miguelofbc, @Alona-T
