### ISSUE TITLE
showInThread is working only for first channel

### ISSUE THREAD

**Issue by Rajkumar502** [ryanrosello-og/playwright-slack-report#51]
when we are passing more then one channels, showInThread is working only for first channel for other channel failure details shown in main channel instead thread

**Comment by ryanrosello-og** [comment]
thanks reporting @Rajkumar502 , I will fix this.

**Comment by ryanrosello-og** [comment]
Fixed in https://github.com/ryanrosello-og/playwright-slack-report/pull/52
