### ISSUE TITLE
How we can send the html report along with the message in slack

### ISSUE THREAD

**Issue by mohit-accuknox** [ryanrosello-og/playwright-slack-report#53]
Is there any way to send the report in html that is generated when the test fails in slack with the message?

**Comment by ryanrosello-og** [comment]
@mohit-accuknox unfortunately this is not supported.  The html report generated by Playwright is not really portable.  Recommendation here is to host the file somewhere e.g. as part of your build artifacts on your CI or post your html results to an s3 bucket and then expose the link to the s3 file as a link in the Slack message.  (See README for example on how to do this)
