### ISSUE TITLE
Can't post attachments

### ISSUE THREAD

**Issue by InfectedG** [ryanrosello-og/playwright-slack-report#58]
I'm missing the attachments and I can't figure out how to add them, here is my layout (default): 

```const web_api_1 = require('@slack/web-api');
const slackClient = new web_api_1.WebClient(process.env.SLACK_BOT_USER_OAUTH_TOKEN);
const SLACK_CHANNEL = process.env.SLACK_CHANNEL;

async function uploadFile(filePath) {
  try {
    const result = await slackClient.files.uploadV2({
      channel_id: 'SLACK_CHANNEL',
      file: fs.createReadStream(filePath),
      filename: filePath.split('/').at(-1),
    });

    return result.file;
  } catch (error) {
    console.log('🔥🔥 error', error);
  }
}

export async function generateCustomDef (summaryResults: SummaryResults): Promise<Array<KnownBlock | Block>> {
  const { tests } = summaryResults;
  // See the snippet above ^^^


    if (t.attachments) {
      for (const a of t.attachments) {
        const file = await uploadFile(a.path);

        if (file) {
          if (a.name === 'screenshot' && file.permalink) {
            fails.push({
              alt_text: '',
              image_url: file.permalink,
              title: { type: 'plain_text', text: file.name || '' },
              type: 'image',
            });
          }

          if (a.name === 'video' && file.permalink) {
            fails.push({
              alt_text: '',
              // NOTE:
              // Slack requires thumbnail_url length to be more that 0
              // Either set screenshot url as the thumbnail or add a placeholder image url
              thumbnail_url: '',
              title: { type: 'plain_text', text: file.name || '' },
              type: 'video',
              video_url: file.permalink,
            });
          }
        }
      }
    }

  return [header, summary, { type: "divider" }, ...fails]
}
```
I don't have any attachments uploaded to my Slack, here is a preview:
![Alt text](https://cdn.discordapp.com/attachments/789472674334113834/1163459229085073468/image.png?ex=653fa6d8&is=652d31d8&hm=c933dd9ab6709ce469ea8dfad6d921509cd7848e3e80b339e7a017f1e197a7b4& "a title")

**Comment by ryanrosello-og** [comment]
hey @InfectedG , sorry for the late reply. Only thing I can suggest is confirming whether you done the following steps:

```
To enable this functionality, make sure the slackbot user has the following additional scopes:

files:write
files:read
You will need to re-install the app and re-invite the bot into the channel.

The value of the channel_id should be the channel id of the channel you want to upload the file to. This channel id can be found in the url when you are in the channel. e.g.

https://app.slack.com/client/T02RVEEFPDH/C05H7TKVDUK

^ the bit starting with 'C...' is your channel id. In this case, the channel id is C05H7TKVDUK
```

**Comment by InfectedG** [comment]
<img width="334" alt="image" src="https://github.com/ryanrosello-og/playwright-slack-report/assets/12138607/bc7e5b03-f39e-4e14-96d6-cdcec26a4058">
Hi! Thanks for the reply, I have all theses scopes + I re-install the app, here is my code: 
`Accepted Scopes: [ 'files:write:user' ]
[
  {
    "channel": "_important",
    "outcome": "❌ Message not sent to _important \r\n An API error occurred: invalid_blocks_format"
  },
  {
    "channel": "_solpaybot_preprod",
    "outcome": "❌ Message not sent to _preprod \r\n An API error occurred: invalid_blocks_format"
  }
]`

My code: 
`import fs from "fs";
import { Block, KnownBlock } from "@slack/types";
import { failure, SummaryResults } from "playwright-slack-report/dist/src";
import moment from "moment";
import { WebClient } from "@slack/web-api";
import ENV from "./src/utils/env";
import DiscordWebhook from "discord-webhook-ts";
import axios from "axios";

// Initialise le client Slack avec le token d'authentification
const slackClient = new WebClient(ENV.SLACK_BOT_USER_OAUTH_TOKEN);
const webhookDiscord = ENV.DISCORD_WEBHOOK;
const discordClient = new DiscordWebhook(`${webhookDiscord}`);
const slackWebhookImportant = ENV.SLACK_WEBHOOK_IMPORTANT?.toString() || "";
const fullStatut = ENV.FULL_STATUT;
const SLACK_CHANNEL = ENV.SLACK_CHANNEL?.toString() || "";

async function uploadFile(filePath: string): Promise<any> {
  try {
    const result = await slackClient.files.uploadV2({
      channels: SLACK_CHANNEL,
      file: fs.createReadStream(filePath),
      filename: filePath.split("/").at(-1),
    });

    return result.file;
  } catch (error) {
    console.log("🔥🔥 error", error);

    if (
      error.code === "slack_webapi_platform_error" &&
      error.data &&
      error.data.response_metadata
    ) {
      const acceptedScopes = error.data.response_metadata.acceptedScopes;
      console.log("Accepted Scopes:", acceptedScopes);
    }
  }
}

export default async function generateCustomLayoutAsync(
  summaryResults: SummaryResults,
  failureData: failure
): Promise<Array<Block | KnownBlock>> {
  const { tests } = summaryResults;
  const t = tests[0];
  const fails: Array<KnownBlock | Block> = [];

  if (t.attachments) {
    for (const a of t.attachments) {
      const file = await uploadFile(a.path);

      if (file) {
        if (a.name === "screenshot" && file.permalink) {
          fails.push({
            alt_text: "",
            image_url: file.permalink,
            title: { type: "plain_text", text: file.name || "" },
            type: "image",
          });
        }

        if (a.name === "video" && file.permalink) {
          fails.push({
            alt_text: "",
            // NOTE:
            // Slack requires thumbnail_url length to be more that 0
            // Either set screenshot url as the thumbnail or add a placeholder image url
            thumbnail_url: "",
            title: { type: "plain_text", text: file.name || "" },
            type: "video",
            video_url: file.permalink,
          });
        }
      }
    }
  }

  const meta: { type: string; text: { type: string; text: string } }[] = [];
  if (summaryResults.meta) {
    for (let i = 0; i < summaryResults.meta.length; i += 1) {
      const { key, value } = summaryResults.meta[i];
      meta.push({
        type: "section",
        text: {
          type: "mrkdwn",
          text: `\n*${key}* :\t${value}`,
        },
      });
    }
  }

  const divider: KnownBlock = {
    type: "divider",
  };
  const header: KnownBlock = {
    type: "header",
    text: {
      type: "plain_text",
      text: `🎭 ${t.suiteName}`,
      emoji: true,
    },
  };

  let startAt = moment(t.startedAt).format("HH:mm:ss"); // 15:09:10
  let endAt = moment(t.endedAt).format("HH:mm:ss"); // 15:09:10
  let timeofTheTest = moment
    .duration(moment(t.endedAt).diff(moment(t.startedAt)))
    .asMinutes()
    .toString()
    .slice(0, 6); // 0.0001 > cut à 6 char max
  let dayToday = moment().format("dddd"); // Monday...
  let numberandMonth = moment().format("MMMM Do"); // March 10th...
  let today = dayToday + ", " + numberandMonth; // Monday, March 10th...
  //console.log(today);

  const timing: KnownBlock = {
    type: "context",
    elements: [
      {
        type: "mrkdwn",
        text:
          `${t.status} | ` +
          `*${timeofTheTest}min elapsed*` +
          " | " +
          `${today}`,
      },
    ],
  };

  const summary: KnownBlock = {
    type: "section",
    text: {
      type: "mrkdwn",
      text: `✅ *${summaryResults.passed}* | ❌ *${summaryResults.failed}* | ⏩ *${summaryResults.skipped}*`,
    },
  };

  // calculate total tests
  const total =
    summaryResults.passed + summaryResults.failed + summaryResults.skipped;
  const infos: KnownBlock = {
    type: "context",
    elements: [
      {
        type: "mrkdwn",
        text: `Route : *${t.suiteName}* ` + " *—* " + ` *${t.name}* `,
      },
      {
        type: "mrkdwn",
        text: `Total test(s): *${total}* `,
      },
      {
        type: "mrkdwn",
        text: `Browser: *${t.projectName}* `,
      },
      {
        type: "mrkdwn",
        text: `Attachments (WIP): *${t.attachments}* `,
      },
    ],
  };

  function sendErrorMessageToDiscord(suiteName: string, reason: string) {
    const embed = {
      title: `SOLPAY debug: ${suiteName}`,
      fields: [
        {
          name: "Error:",
          value: reason,
        },
      ],
    };
    discordClient
      .execute({ embeds: [embed] })
      .then((response) => {
        console.log("Successfully sent webhook.");
      })
      .catch((error) => {
        console.error("Error sending Discord webhook:\n", error);
      });
  }

  function sendErrorMessageToSlack(suiteName: string, reason: string) {
    const payload = {
      text: `${reason}`,
    };

    axios
      .post(slackWebhookImportant, payload)
      .then((response) => {
        console.log(response.data);
      })
      .catch((error) => {
        console.error("Error sending Slack webhook:\n", error);
      });
  }

  const logs: Array<KnownBlock | Block> = [];
  const arrayErrors: string[] = [
    // Compléter le mot-clé pour se faire ping
    "is full due to",
    "maybe frame was detached?",
    "apiRequestContext",
    "apiRequestContext.post: Request timed out after 30000ms",
  ];

  if (summaryResults.failed > 0) {
    for (let i = 0; i < summaryResults.tests.length; i += 1) {
      const test = summaryResults.tests[i];
      if (
        test.status === "failed" ||
        test.status === "skipped" ||
        test.status === "timedOut"
      ) {
        let matchFound = false;
        for (const str of arrayErrors) {
          if (t.reason.includes(str)) {
            matchFound = true;
            break;
          } else {
            //insérer durée du test en base

          }
        }

        if (matchFound) {
          console.log("String detected");
          //sendErrorMessageToDiscord(t.suiteName, t.reason);
          //sendErrorMessageToSlack(t.suiteName, t.reason);
          logs.push({
            type: "context",
            elements: [
              {
                type: "mrkdwn",
                text: "``` " + `${t.reason}` + " ```",
              },
            ],
          });
        }
      }
    }
  }

  const files: KnownBlock = {
    type: "context",
    elements: [
      {
        type: "mrkdwn",
        text: "<https://google.com/|🐞  Trace Viewer (WIP)> — <https://google.com|📊  View metrics>",
      },
    ],
  };

  const footer: KnownBlock = {
    type: "context",
    elements: [
      {
        type: "image",
        image_url: "https://www.google.fr/logos/2023/storybook/h23-14014/cta.gif",
        alt_text: "Google Logo",
      },
      {
        type: "mrkdwn",
        text: `v1.2.3, LU20231012 @${fullStatut} | Powered by Docker & Playwright, running on Debian 11`,
      },
    ],
  };

  return [
    header,
    timing,
    divider,
    summary,
    infos,
    ...logs,
    files,
    divider,
    footer,
  ];
}
`

**Comment by InfectedG** [comment]
Hi I have another question too: can we use a different channel for diff env? I'm guessing yes because we can use different oauth :), still the same block problem, I can't really see where it's going wrong
