### ISSUE TITLE
Provide a fallback summary text

### ISSUE THREAD

**Issue by pavelkostyurin** [ryanrosello-og/playwright-slack-report#59]
Currently there is no text provided in mobile notification. In order to see results, you have to click it and go to slack.
It would be great if you could provide a fallback text, so summary would be displayed right in the notification.

From https://api.slack.com/messaging/composing/layouts#add_blocks_array :
> When you're using blocks in your message payload, the top-level text field becomes a fallback message displayed in notifications. Blocks should define everything else about the desired visible message.

**Comment by ryanrosello-og** [comment]
thanks,  I will look into this

**Comment by ryanrosello-og** [comment]
Update to v1.1.25 @pavelkostyurin
