### ISSUE TITLE
Modify Thread Content

### ISSUE THREAD

**Issue by burakboluk** [ryanrosello-og/playwright-slack-report#60]
I want to run my project on CircleCI and get the reports on Slack. I want to get the failures in a thread since they take too much space. I can edit fails[] in the layout/block generator under src, but it doesn't affect thread messages. I have to edit node modules, but that doesn't work with CircleCI.

**Comment by ryanrosello-og** [comment]
Altering the layout of the threads is currently not supported.  I will look into supporting this.
