### ISSUE TITLE
Wrong test count when separateFlaky = true

### ISSUE THREAD

**Issue by pavelkostyurin** [ryanrosello-og/playwright-slack-report#61]
Something is not right with this option enabled.

I run 1 auth.setup.ts and 18 tests (including 1 skipped) across 8 browsers, totaling in 145 tests.

In logs I can see
```
Running 145 tests using 1 worker
················°·················°·················°·················°·········
········°·················°·················°·················°··✅ Message sent to xxx
[
  {
    "channel": "xxx",
    "outcome": "✅ Message sent to xxx",
    "ts": "1699552045.523659"
  }
]

  8 skipped
  137 passed (12.8m)
  ```
Although in Slack I can see `120 | 0 | 0 | 8`

Without this option it was `137 | 0 | 8`, as it should be.

**Comment by ryanrosello-og** [comment]
@pavelkostyurin Can you confirm that you are using the latest version? Pretty this was already fixed.

**Comment by ryanrosello-og** [comment]
hmm, yeah I can see this still an issue.  I can somewhat reproduce here...
![2023-11-11_05-53-26](https://github.com/ryanrosello-og/playwright-slack-report/assets/50574915/d75cc08f-24ca-49dc-856e-545704487512)

Lemme fix
