### ISSUE TITLE
[Question] How to send message to different channels with different sendResults

### ISSUE THREAD

**Issue by SlawomirMankaGtxn** [ryanrosello-og/playwright-slack-report#69]
What I am trying to achieve is to send notifications to two channels but with different sendResults:
'automation-tests' -> always
'monitoring' -> on-failure

One channel will get messages only when tests fail, but the second should get all reports whether they are failing or not. 
I tried to create two similar reporters with different channels and sendResults but it won't work as I expected (send two messages to the first channel )

Is there a way to achieve it?

**Comment by mickael-h** [comment]
Same question here, albeit slightly different.
We would like to send successes to a specific channel and failures to another channel.
"test-success" -> on-success
"test-failure" -> on-failure

**Comment by ryanrosello-og** [comment]
this is a good idea, currently not supported though.  I will work to implement this for you

**Comment by ryanrosello-og** [comment]
This has been released in v1.1.60 
Thanks @m-kusnierz 👍
