### ISSUE TITLE
getting module_not_found error

### ISSUE THREAD

**Issue by irtezakhan** [ryanrosello-og/playwright-slack-report#72]
![Screenshot 2023-12-07 at 6 25 32 PM](https://github.com/ryanrosello-og/playwright-slack-report/assets/36564192/14728c3b-eaa2-4513-abe5-5d315e541266)

**Comment by irtezakhan** [comment]
playwright-slack-report was installed and is available in the node_modules folder

**Comment by irtezakhan** [comment]
i want to ask that is the documentation up to date with the latest implemenation? and is it fully compatible with playwright in javascript instead of typescript

**Comment by ryanrosello-og** [comment]
@irtezakhan , this will only work using Typescript based Playwright projects.
