### ISSUE TITLE
How to mention someone in slack channel when a test fail

### ISSUE THREAD

**Issue by lychanminh91** [ryanrosello-og/playwright-slack-report#76]
Hi, thank you for your work!

Is there a way for me to mention a user in slack or use @here or @channel when a test fail?

**Comment by ryanrosello-og** [comment]
hi @lychanminh91 

You can either try using a custom meta in the config:

![2023-12-13_20-40-02](https://github.com/ryanrosello-og/playwright-slack-report/assets/50574915/be3aa387-48b8-40d1-813b-5be9db947962)

Or define your own customLayout and have a text block performing the mentions inside one of the blocks
