### ISSUE TITLE
CLI option does not handle dynamic meta data

### ISSUE THREAD

**Issue by saulius-skarulskis** [ryanrosello-og/playwright-slack-report#79]
I am using option C to send results to Slack. I started with example configuration like this:
```
{
  "sendResults": "always",
  "slackLogLevel": "error",
  "sendUsingBot": {
    "channels": ["demo"]
  },
  "showInThread": true,
  "meta": [
    { "key": "build", "value" : "{__ENV_BUILD_ID}"},
    { "key": "branch", "value" : "{__ENV_BRANCH_NAME}"},
    { "key": "commit", "value" : "{__ENV_COMMIT_ID}"},
    { "key": "results", "value" : "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"}
  ],
  "maxNumberOfFailures": 4,
  "disableUnfurl": true
}
```
But what I get in Slack is this:
![image](https://github.com/ryanrosello-og/playwright-slack-report/assets/98949294/817cb26b-2af8-44b9-a536-4514aaefcad8)
It looks like it does not process these environment variables. According to documentation it shouldn't let me sent it because I don't have these variables defined. It should output an error... Is there something I am doing wrong? Or is it just broken?

**Comment by ryanrosello-og** [comment]
@saulius-skarulskis think theres a bug in the doco, can you try without the curly branches?

e.g.

```
  "meta": [
    { "key": "build", "value" : "__ENV_BUILD_ID"},
    { "key": "branch", "value" : "__ENV_BRANCH_NAME"},
    { "key": "commit", "value" : "__ENV_COMMIT_ID"},
    { "key": "results", "value" : "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"}
  ],
```

**Comment by saulius-skarulskis** [comment]
It works! So its just documentation bug. Thanks 👍
