### ISSUE TITLE
Having issue to receive the slack notification

### ISSUE THREAD

**Issue by mierzater** [ryanrosello-og/playwright-slack-report#8]
Hi, I followed the step to configure my playwright project and also set up the slack app, and invited it to the specific channel. When i run the test it shows an error, do you know what causes the issue?

Error msg:
```
[DEBUG]  web-api:WebClient:0 initialized
[DEBUG]  web-api:WebClient:0 apiCall('chat.postMessage') start
[DEBUG]  web-api:WebClient:0 will perform http request
[DEBUG]  web-api:WebClient:0 http response received
```

playwright.config.js:
```
  reporter: [
    ["./node_modules/playwright-slack-report/dist/src/SlackReporter.js", {
      channels: ["regression-test"],
      sendResults: "always",
    },
    ]
  ]
```

**Comment by ryanrosello-og** [comment]
hey, @mierzater the messages you see are debug messages not errors. Typically it will print the following:

```
[DEBUG]  web-api:WebClient:0 initialized
[DEBUG]  web-api:WebClient:0 apiCall('chat.postMessage') start
[DEBUG]  web-api:WebClient:0 will perform http request
[DEBUG]  web-api:WebClient:0 http response received
✅ Message sent to automated-tests
```

I can turn off the debug message above if it gets annoying.

**Comment by mierzater** [comment]
but I didn't receive any notification in the slack channel.

**Comment by ryanrosello-og** [comment]
@mierzater can you please upgrade to v1.0.14 and rerun.  I have added extra logs in https://github.com/ryanrosello-og/playwright-slack-report/pull/10 to help troubleshoot your issue.

**Comment by mierzater** [comment]
it works perfectly fine now, thank you.
