### ISSUE TITLE
The CLI currently does not support custom layouts. I want to handle dynamic meta data different then environment variables storing your build id, branch name etc

### ISSUE THREAD

**Issue by IvayloStoychev** [ryanrosello-og/playwright-slack-report#86]
Is there any way to adjust the cli_config.json file to send a customised message like my previous message generated through the reported in `playwright.config.ts` file

Generated through CLI slack reporter:

![image](https://github.com/ryanrosello-og/playwright-slack-report/assets/132457997/a5deb2ef-878e-4dcd-87b9-91d51d84b019)

Generated through `playwright.config.ts slack` reporter:

![image](https://github.com/ryanrosello-og/playwright-slack-report/assets/132457997/c3b58fd2-a153-403b-a8f4-fa2c6cd828e8)

Like, how to add divider, how to send different mrkdwn lines in the message, can I bold some text, can I add some description for the passed/failed tests (like in the screenshot 2).

**Comment by ryanrosello-og** [comment]
this has been implemented in 1.1.70

create the following file `cli_custom_layout.ts` with the following contents and tweak it to suit your needs:

```
function generateCustomLayoutSimpleMeta(summaryResults) {
  const meta = [];
  if (summaryResults.meta) {
    for (let i = 0; i < summaryResults.meta.length; i += 1) {
      const { key, value } = summaryResults.meta[i];
      meta.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `\n*${key}* :🙌\t${value}`,
        },
      });
    }
  }
  return [
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text:
          summaryResults.failed === 0
            ? ':tada: All tests passed!'
            : `😭${summaryResults.failed} failure(s) out of ${summaryResults.tests.length} tests`,
      },
    },
    ...meta,
  ];
}
exports.generateCustomLayoutSimpleMeta = generateCustomLayoutSimpleMeta;
```

**NOTE:** 
* this file should not have any `import` statements, I couldn't quite figure out how to get nested dynamic imports to work properly
* it should have an export statement:
`exports.generateCustomLayoutSimpleMeta = generateCustomLayoutSimpleMeta;`

You will then need to update your config file to use this custom layout file:

e.g.

```

{
  "sendResults": "always",
  "slackLogLevel": "error",
  "sendUsingBot": {
    "channels": ["demo"]
  },
  "showInThread": true,
  "meta": [
    { "key": "build", "value": "__ENV_blah" },
    { "key": "branch", "value": "master" },
    { "key": "commit", "value": "1234567890" },
    {
      "key": "results",
      "value": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
    }
  ],
  "maxNumberOfFailures": 1,
  "disableUnfurl": true,
  "customLayout": {
    "source": "./wherever_you_stored_the_file/cli_custom_layout.ts",
    "functionName": "generateCustomLayoutSimpleMeta"
  }
}

```

give this a shot @IvayloStoychev

**Comment by IvayloStoychev** [comment]
Hey @ryanrosello-og thanks for the provided update. However I test the suggested actions and unfortunately this custom layout config is not present in my slack report at all. 
Please find the files and actions that I did in order to test it. 
I have been create a `cli_custom_layout.ts` in my root directory of the tests with following content inside: 

`export function generateCustomLayoutSimpleMeta(summaryResults: { meta: string | any[]; failed: number; tests: string | any[]; }) {
  const meta = [];
  if (summaryResults.meta) {
    for (let i = 0; i < summaryResults.meta.length; i += 1) {
      const { key, value } = summaryResults.meta[i];
      meta.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `\n*${key}* :🙌\t${value}`,
        },
      });
    }
  }
  return [
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text:
          summaryResults.failed === 0
            ? ':tada: All tests passed!'
            : `😭${summaryResults.failed} failure(s) out of ${summaryResults.tests.length} tests`,
      },
    },
    ...meta,
  ];
}
exports.generateCustomLayoutSimpleMeta = generateCustomLayoutSimpleMeta;`

My `cli_config.json` have the following structure:

`{
    "sendResults": "always",
    "slackLogLevel": "error",
    "sendUsingBot": {
      "channels": ["test_auto_slack_message"]
    },
    "showInThread": true,
    "meta": [
      { "key": "Name", "value": "__ENV_REPORT_NAME"}, 
      { "key": "Report link", "value": "__ENV_RESULT_URL"}
    ],
    "disableUnfurl": true,
    "customLayout": {
      "source": "./custom_slack_layout.ts",
      "functionName": "customLayoutSimpleMeta"
    }
  }
`

And the slack message generated after that is not updated at all and the new layout is not displayed in all cases (when I have passed and/or failed tests). Check screenshot below:

<img width="370" alt="image" src="https://github.com/ryanrosello-og/playwright-slack-report/assets/132457997/84db221e-4c11-449f-9328-135cbda6bf74">

Could you please if there is something that I am missing in my files and configurations or suggest some other actions to try in my project. 
THanks in advance

**Comment by IvayloStoychev** [comment]
Hey @ryanrosello-og thank you for the provided update. I test the slack message generator based on the latest correction that you mention, however I am still not receiving the data generated in `cli_custom_layout.ts`. Please find my code bellow:
 Here is my `cli_custom_layout.ts` file content, as I tested the behaviour with and without  symmaryResults parameters `{ meta: string | any[]; failed: number; tests: string | any[]; }` and the results was still the same
 
 
 ```
 // @ts-ignore
function generateCustomLayoutSimpleMeta(summaryResults: { meta: string | any[]; failed: number; tests: string | any[]; }) {
  const meta = [];
  if (summaryResults.meta) {
    for (let i = 0; i < summaryResults.meta.length; i += 1) {
      const { key, value } = summaryResults.meta[i];
      meta.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `\n*${key}* :🙌\t${value}`,
        },
      });
    }
  }
  return [
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text:
          summaryResults.failed === 0
            ? ':tada: All tests passed!'
            : `😭${summaryResults.failed} failure(s) out of ${summaryResults.tests.length} tests`,
      },
    },
    ...meta,
  ];
}
exports.generateCustomLayoutSimpleMeta = generateCustomLayoutSimpleMeta;
```

Here is my `cli_config.json`: 
```
{
    "sendResults": "always",
    "slackLogLevel": "error",
    "sendUsingBot": {
      "channels": ["test_auto_slack_message"]
    },
    "showInThread": true,
    "meta": [
      { "key": "Name", "value": "__ENV_REPORT_NAME"}, 
      { "key": "Report link", "value": "__ENV_RESULT_URL"}
    ],
    "disableUnfurl": true,
    "customLayout": {
      "source": "./cli_custom_layout.ts",
      "functionName": "generateCustomLayoutSimpleMeta"
    }
  }

```
I am still getting the regular slack message, without meta data in it for both with and without failures in the tests:

<img width="388" alt="image" src="https://github.com/ryanrosello-og/playwright-slack-report/assets/132457997/73006a3d-61d2-422b-aeaf-401065823cf8">

Please advice about this ? Is there something wrong with code ? Is it working on your side ?

**Comment by IvayloStoychev** [comment]
@ryanrosello-og Thanks for the update. After I update my slack reporter to the latest version: `"playwright-slack-report": "^1.1.70",` the slack message is working as expected.
