### ISSUE TITLE
Send playwright test results message to slack channels based on test tags

### ISSUE THREAD

**Issue by RAZAW** [ryanrosello-og/playwright-slack-report#89]
We have a situation where a number of tests are run in pipelines. These tests are owned by different teams and the tests are tagged by the team name e.g. team power's tests would have a tag @power. The channels are also named as such mycompany-power. Is there a way to send a message to a channel based on test tag? So if a test tagged with @power fails, we send a message to mycompany-power but not to the other channels as it is not relevant information for them. Thanks in advance for your help.

**Comment by ryanrosello-og** [comment]
The simplest way I can think of is to expose the test tag via an Environment variable?

e.g.
somewhere in your test suite ...

`process.env.TEST_TAG = '@power'`

And then add logic to the channels key

```javascript
  reporter: [
    [
      './src/SlackReporter.ts',
      {
        channels: process.env.TEST_TAG === '@power' ? ['mycompany-power'] : ['the-other-channel'],
        sendResults:  "on-failure"
        ...
      },
    ],
  ],

```
