### ISSUE TITLE
Surpressing [DEBUG] messages in the console output doesn't seem to work

### ISSUE THREAD

**Issue by azad-resolver** [ryanrosello-og/playwright-slack-report#92]
I've noticed that the console output of the SlackReporter is full of `[DEBUG]` messages, is there a way to surpress them in my custom layout file for the SlackReporter?

<img width="195" alt="image" src="https://github.com/ryanrosello-og/playwright-slack-report/assets/131415063/77bb7791-4924-4ef8-9cda-ddd99a715415">

I've had previously used this module in a different project/job and afair it didn't print out those debug messages before.
Would appreciate your help on this!

Edit: I already tried it with setting `slackLogLevel: "ERROR",` in the config but it still prints out the debug messages.

**Comment by azad-resolver** [comment]
I'm using it via a Slack bot user.

Here's my config (slightly modified) as well the custom layout:

[config.zip](https://github.com/ryanrosello-og/playwright-slack-report/files/14215679/config.zip)

**Comment by ryanrosello-og** [comment]
I can't seem to repro:
I tried both `slackLogLevel: 'ERROR',` and `slackLogLevel: 'error',`
Also with/without customLayout.

Which version are you running with?

<img width="1154" alt="2024-02-10_15-22-16" src="https://github.com/ryanrosello-og/playwright-slack-report/assets/50574915/c5f1fabc-c8e1-4125-a0af-983fb58d2d8c">

**Comment by azad-resolver** [comment]
> Which version are you running with?

You know what, I was apparently running on an older version (1.1.16) and now after updating the issue doesn't occur anymore. 🤦 Sorry about that, I'll close this ticket.
