### ISSUE TITLE
"on-failures" sending alerts to Slack with zero failures + flakes + expected skips

### ISSUE THREAD

**Issue by Zanzibarbarian** [ryanrosello-og/playwright-slack-report#93]
## Background

I've set up the Slack reporter via the Slack Oauth token, with the "on-failures" sendResults attribute.

Recently, I've skipped a handful of tests via the `test.skip(browserName == 'webkit');` implementation. There are 4 expected skips in my suite. This, as far as I can tell, is the only change I've made resulting in the outcome below.

This morning, on my nightly run, the reporter sent an alert to Slack with 94 passes, zero failures, 4 flakes, and 4 skips:
:white_check_mark: 94 | :x: 0 | 🟡 4 | :fast_forward: 4

## Expectations

I would have expected no alert in this scenario, as there were no failures.

## Code

```
reporter: 
    process.env.CI ?
      [
        [
          "./node_modules/playwright-slack-report/dist/src/SlackReporter.js",
          {
            channels: ["playwright-alerts"], // provide one or more Slack channels
            sendResults: "on-failure", // "always" , "on-failure", "off"
          },
        ],
        ["html"],
      ]: [["html"]],
```

## Question

Can I modify my implementation so that this scenario doesn't send an alert to Slack in the future?

**Comment by ryanrosello-og** [comment]
Lemme take a look, I suspect flakey tests are being treated as failures

**Comment by ryanrosello-og** [comment]
@Zanzibarbarian update to v1.1.71 - should be fixed now

**Comment by Zanzibarbarian** [comment]
Thanks!
