### ISSUE TITLE
Trace viewer/timeline addition

### ISSUE THREAD

**Issue by bibas07** [ryanrosello-og/playwright-slack-report#95]
I saw configuration in meta with HTML result but not in notification with AWS so is this possible to attach to HTML result with video/screenshot? If yes, can you explain solution.

**Comment by ryanrosello-og** [comment]
Hey @bibas07 are you wanting to attach links to artifacts stored in s3? Or something else?
There's an example in the readme:

<img width="1407" alt="Snag_52d4c3e" src="https://github.com/ryanrosello-og/playwright-slack-report/assets/50574915/ce48fca6-37a5-4a60-8867-99e004b944b9">

**Comment by bibas07** [comment]
these are screenshot and video. I want timeline 
![Uploading Screenshot 2024-02-22 221547.png…]()
