### ISSUE TITLE
How to send failure details using webhook option

### ISSUE THREAD

**Issue by aakashgupt** [ryanrosello-og/playwright-slack-report#97]
as per readme file, Sending failure details in a thread is not supported when using webhooks. You will need to use Option B below. 

This doesn't answer that can it be sent in any other way or sending failures is not supported at all? 
Do you have an example to resolve this?

**Comment by aakashgupt** [comment]
I came across this [thread](https://github.com/ryanrosello-og/playwright-slack-report/issues/71). Can you answer that could I send failed tests inside the main slack notification?

**Comment by ryanrosello-og** [comment]
@aakashgupt webhooks does not support threads

> Can you answer that could I send failed tests inside the main slack notification?

thats the default behaviour. Can you elaborate what exactly you are trying to do?
